# Generated by Django 3.2.5 on 2021-08-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0002_sandwich_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='salesite.Ingredient'),
        ),
    ]
